export const JOKE_GET_REQUEST = "JOKE_GET_REQUEST";
export const JOKE_GET_SUCCESS = "JOKE_GET_SUCCESS";
export const JOKE_GET_FAILURE = "JOKE_GET_FAILURE";

export const CATEGORIES_GET_REQUEST = "CATEGORIES_GET_REQUEST";
export const CATEGORIES_GET_SUCCESS = "CATEGORIES_GET_SUCCESS";
export const CATEGORIES_GET_FAILURE = "CATEGORIES_GET_FAILURE";